### ISSUE TITLE
优化建议：芯片计算器-芯片仓库

### ISSUE THREAD

**Issue by RookieTester** [hycdes/GFTool#5]
描述：芯片仓库table，最左侧能否新增一列CheckBox，支持多选，这样可以一次性删除多个芯片。
原因：想到这个优化的原因是，我拼完一个重装的最优解后，再给另一个重装拼，为了不重复，打算删掉已经使用的，按序号去找，结果发现芯片仓库一次只能删一个，但是每删完一个，芯片仓库的所有芯片会重新排序，我也得重新找序号，还是有些麻烦，看能否优化一下

**Comment by hycdes** [comment]
试着写了个，但有个问题是，默认checked，即使勾选改变checked=false，再添加新条目，原checkbox又会变成勾选状态，即使console出来依旧是false……这个具体不知道是为啥，没搜到，蛮奇怪的，所以搁置了
